import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFileSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
const root = '/home/user/Chart/app/dist';
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.map': 'application/json' };
const srv = createServer((req, res) => { let p = join(root, req.url.split('?')[0] === '/' ? 'index.html' : req.url.split('?')[0]); if (!existsSync(p)) { res.statusCode = 404; res.end(); return; } res.setHeader('content-type', types[extname(p)] ?? 'application/octet-stream'); res.end(readFileSync(p)); });
await new Promise((r) => srv.listen(4567, r));
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
await page.goto('http://localhost:4567/');
await page.waitForTimeout(2500);
const out = process.env.SHOT_DIR ?? '/tmp/claude-0/-home-user-Chart/c70a520e-8bab-58d7-8743-66a5bb1e1e91/scratchpad/';
await page.screenshot({ path: out + 'shot1.png' });
// open tours, start tour 7 step 3 (P4 subalgebra) and go to graph
await page.getByText('Tours', { exact: true }).click();
await page.selectOption('select.tour-select', { index: 1 });
await page.getByText('start').click();
await page.waitForTimeout(500);
await page.getByText('next ›').click(); await page.getByText('next ›').click();
await page.waitForTimeout(1500);
await page.screenshot({ path: out + 'shot2.png' });
// facts panel
await page.getByText('Facts', { exact: true }).click();
await page.waitForTimeout(3000);
await page.screenshot({ path: out + 'shot3.png' });
// zero divisors tab, pick first class
await page.getByText('Zero divisors', { exact: true }).click();
await page.waitForTimeout(1500);
const rows = page.locator('table.grid tbody tr');
await rows.first().click();
await page.getByText('Console', { exact: true }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: out + 'shot4.png' });
const txt = await page.locator('.console-out').innerText();
console.log('console panel:', txt.slice(0, 300));
console.log('errors:', errors.length ? errors.join('\n') : 'none');
await browser.close(); srv.close();
