import type { Selection } from './state/store';

export interface TourStep { caption: string; preset?: string; select?: Selection; panel?: string; overlay?: 'none' | 'chi' | 'types'; gridD?: number }
export interface Tour { id: number; title: string; steps: TourStep[] }

// bitmask indices: o1=1 o2=2 o12=3 o3=4 o13=5 o23=6 o123=7 o4=8 o14=9 o24=10 o124=11 o34=12 o134=13 o234=14 o1234=15
export const TOURS: Tour[] = [
  { id: 6, title: 'Wilmot I: types and silos', steps: [
    { caption: 'The octonions: every non-associative triad is type X (all three of Wilmot\'s associativity classes fail). Open the triad explorer: 35 triads, 7 associative lines, 28 of type X, eight XXX 3-triad cycles.', preset: 'O', panel: 'triads' },
    { caption: 'The sedenions add two more types. Triad (o1, o2, o34) is type A: [o1, o34, o2] = −2 o1234 while [o1, o2, o34] = [o2, o1, o34] = 0. The table highlights the four products that enter the associator.', preset: 'S', select: { triad: [1, 2, 12] }, panel: 'table' },
    { caption: 'Triad (o1, o24, o34) is type C: only the third class [c, b, d] fails. Compare its Moufang bits with the type-A triad: Moufang 1 holds for B or X only, Moufang 2 for C or X only.', preset: 'S', select: { triad: [1, 10, 12] }, panel: 'triads' },
    { caption: 'Silos: each first-cycle triad (b, c, d) with b < c < bc < d has two cycle mates (b, bc, d) and (c, bc, d). Only eight type patterns occur; in S the silos are AAA (28), CCX (28) and XXX (64). Filter the explorer to first-cycle triads.', preset: 'S', panel: 'triads' },
    { caption: 'The trigintaduonions introduce type B and the silos BBA and ACC; U3 adds XBB and BXC, U4 adds CAB. Facts shows the full Table 4 for each preset.', preset: 'T', panel: 'facts' },
  ] },
  { id: 7, title: 'Wilmot II: octonions and quasi-octonions in S', steps: [
    { caption: 'The 15 basis hyperplanes of S split 8 octonion copies and 7 quasi-octonions P4 = M(H). The lattice lists them by type.', preset: 'S', panel: 'lattice' },
    { caption: 'An octonion copy: the hyperplane generated by (o1, o2, o4). All 28 of its non-associative triads are type X, and its block in the table has no leakage.', preset: 'S', select: { basis: [1, 2, 8] }, panel: 'graph' },
    { caption: 'A quasi-octonion: generated by (o1, o2, o34). Its 28 triads are 12 A, 12 C, 4 X. In the structure graph its seven lines mix orientations.', preset: 'S', select: { basis: [1, 2, 12] }, panel: 'graph' },
    { caption: 'Each P4 copy carries 12 two-term zero-divisor pairs; with seven copies that is 7 × 12 = 84, Wilmot\'s Z_1. The catalog groups them into the seven cycle/mode classes of Table 9.', preset: 'S', panel: 'zd' },
    { caption: 'The first primary: (o1 − o1234)(o2 + o34) = 0. Its dual, extended and extended-dual modes are all zero divisors too.', preset: 'S', select: { zd: { b: 1, c: 2, d: 12, a: 15, sa: -1 } }, panel: 'zd' },
  ] },
  { id: 8, title: 'Wilmot III: 32 to 128', steps: [
    { caption: 'U2 = T: 4495 triads, 155 lines, silos AAA 252, BBA 168, ACC 84, CCX 336, XXX 400. Table 5: 155 H, 50 O, 63 P4, 42 P12. Zero divisors: 1260 = 15 × 84.', preset: 'T', panel: 'facts' },
    { caption: 'By graded isomorphism every one of the 105 quasi-octonions of T is a copy of M(H): Wilmot\'s P12 label depends on the ordering of the basis. The lattice uses the isomorphism-invariant classification.', preset: 'T', panel: 'lattice' },
    { caption: 'U3 (64 dimensions): 39 711 triads, XBB and BXC silos appear, 13 020 zero divisors = 155 × 84.', preset: 'U3', panel: 'facts' },
    { caption: 'U4 (128 dimensions): 333 375 triads, all eight silos including CAB, 117 180 zero divisors = 1395 × 84, exactly (N−1)(N−3)(N−7)/16 with N = 127. The table stays exact at this size.', preset: 'U4', panel: 'table' },
  ] },
  { id: 10, title: 'Mirror I: one letter', steps: [
    { caption: 'The sedenions S = CD(O) with the standard product (ac − d̄b, da + bc̄).', preset: 'S', panel: 'table' },
    { caption: 'The mirror sedenions S′ = M(O) use (ca − d̄b, da + bc̄): the founding octave is multiplied backwards, so e1 e2 = −e3. Toggle the χ overlay to see exactly the 42 cells where the two sign functions differ.', preset: "S'", overlay: 'chi', panel: 'table' },
    { caption: 'χ is −1 on distinct non-zero pairs of the founding F2³ and +1 elsewhere. It is not a 2-cocycle, and no signed relabelling carries S to S′: the graded-isomorphism search over GL(4,2) finds none, while each algebra has 2688 graded automorphisms.', preset: "S'", overlay: 'chi', panel: 'facts' },
    { caption: 'Both algebras are flexible, quadratic and power-associative with Der = g2, yet S′ has 112 two-term zero divisors against 84, and annihilators of dimension 2 or 6 against 4.', preset: "S'", panel: 'facts' },
  ] },
  { id: 11, title: 'Mirror II: inside T', steps: [
    { caption: 'The trigintaduonions T = CD(S) have 31 basis hyperplanes: 16 copies of S, one copy of S′, and 14 others.', preset: 'T', panel: 'lattice' },
    { caption: 'S′ is the hyperplane S_γ spanned by e0…e7 and e24…e31, generated by (e1, e2, e4, e24): the octonions together with the composite unit ℓ e′. This is the embedding Φ(a + bℓ) = ā + (be)e′.', preset: 'T', select: { basis: [1, 2, 4, 24] }, panel: 'graph' },
    { caption: 'Octave configurations in PG(3,2): in S the eight octonion hyperplanes are the founding octave plus the seven through the doubling point ℓ; in S′ they are the eight avoiding ℓ. The census panel shows both.', preset: "S'", panel: 'census' },
  ] },
  { id: 14, title: "Bales's eight products", steps: [
    { caption: 'Bales lists 32 candidate doubling formulas. Applied once over O they give exactly two algebras: P0, P3, P0ᵀ, P3ᵀ give S and P1, P2, P1ᵀ, P2ᵀ give S′. Run the Bales census.', preset: 'S', panel: 'census' },
    { caption: 'The other 24 formulas all have 14-dimensional derivation algebras; 20 keep only the founding octave among their hyperplanes and 4 have eight octaves without being S or S′. Only the eight admissible ones keep every basis line a quaternion algebra along a uniform tower.', preset: 'Bales:P2', panel: 'facts' },
    { caption: 'The sign-function census settles Question 2 at dimension 16: with quaternion lines and a standard founding octave, exactly three graded-isomorphism classes have eight octaves — S, S′, and a third algebra with an 8-dimensional derivation algebra — and none has nine.', preset: "S'", panel: 'census' },
  ] },
];
